{{- range $key, $val := $.Values.global.apps }}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: triggertemplate-{{ $key }}-build
spec:
  params:
    - name: git-url
    - name: git-branch
    - name: git-commit
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: code-$(uid)
      spec:
        type: git
        params:
          - name: revision
            value: $(tt.params.git-commit)
          - name: url
            value: $(tt.params.git-url)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: tests-$(uid)
      spec:
        type: git
        params:
          - name: revision
            value: {{ $.Values.functTestRepoBranch }}
          - name: url
            value: {{ $.Values.functTestRepo }}
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: run-{{ $key }}-$(uid)
      spec:
        pipelineRef:
          name: pipeline-{{ $key }}-build
        resources:
          - name: source-repo
            resourceRef:
              name: code-$(uid)
          - name: functional-test-repo
            resourceRef:
              name: tests-$(uid)
        params:
          - name: git-branch  
            value: $(tt.params.git-branch)
          - name: git-commit  
            value: $(tt.params.git-commit)
          - name: helm-git-url
            value: {{ $.Values.helmGitUrl }}
          - name: helm-git-revision
            value: {{ $.Values.helmGitRevision }}
        workspaces:
          - name: app-helm-source
            persistentVolumeClaim:
              claimName: pipeline-{{ $key }}-build-workspace-pvc
                
{{- end }}
